### ISSUE TITLE
Error: Non-Error exception captured with keys: message

### ISSUE THREAD

**Issue by yurydelendik** [wasdk/WebAssemblyStudio#350]
https://sentry.io/webassembly-studio/webassembly-studio/issues/586289329/

```
Error: Non-Error exception captured with keys: message
  at captureException (./node_modules/raven-js/src/raven.js:500:1)
  at q._promiseRejectionHandler (./node_modules/raven-js/src/raven.js:431:1)

Non-Error exception captured with keys: message
```

**Comment by yurydelendik** [comment]
https://sentry.io/share/issue/3a9ee90e9bdf470a92f9ad46e1a81fb8/
