### ISSUE TITLE
AssemblyScript project builds unsuccessfully

### ISSUE THREAD

**Issue by LiaoPeng** [wasdk/WebAssemblyStudio#398]
The [example](https://webassembly.studio/?f=zktgii6715o)
When I build the project, I got the below hits.
```
ERROR: Entry file 'main.ts' not found.
    at exports.main (https://cdn.jsdelivr.net/gh/AssemblyScript/assemblyscript/dist/asc.js:1:361155)
    at Object.asc.main.main (eval at d (https://webassembly.studio/dist/main.bundle.js:1:32474), <anonymous>:20:12)
    at r.gulp.task.callback [as promiseMaker] (eval at gulp (https://webassembly.studio/dist/main.bundle.js:1:34094), <anonymous>:7:7)
    at o.makePromise (https://webassembly.studio/dist/main.bundle.js:1:31659)
    at s.runInstance (https://webassembly.studio/dist/main.bundle.js:1:31955)
```

I expected building successfully.

**Comment by yurydelendik** [comment]
Probably fixed by #396
